# config.py
"""
DO NOT EDIT THIS FILE.
Edit YAML files in configs/ directory instead.

This is an internal module that loads YAML configs.
"""

from pathlib import Path
import random
import numpy as np

# Lazy torch import to avoid import errors in IDE
_torch = None
def _get_torch():
    global _torch
    if _torch is None:
        import torch
        _torch = torch
    return _torch


class CFG:
    """Configuration container. Loaded from YAML."""

    __slots__ = [
        'video_folder', 'csv_path', 'cache_dir',
        'video_id_col', 'video_path_col', 'target_col', 'start_col', 'end_col', 'stratify_col',
        'img_size', 'n_frames',
        'backbone', 'window_size', 'aggregator',
        'use_classifier', 'cls_weight', 'num_classes', 'cls_thresholds',
        'loss_fn', 'loss_config', 'loss_preset',
        'epochs', 'batch_size', 'grad_accum', 'lr', 'wd', 'workers', 'seed',
        'threshold', 'use_weighted_sampler',
        'n_folds', 'fold_set_prefix', 'set_col',
        'output_dir', 'run_name', 'device', 'exp_dir'
    ]

    def __init__(self, **kwargs):
        # Defaults
        defaults = {
            'video_folder': '', 'csv_path': '', 'cache_dir': '',
            'video_id_col': 'video', 'video_path_col': 'video_path',
            'target_col': 'PDFF', 'start_col': 'start_time_1', 'end_col': 'end_time_1',
            'stratify_col': 'stage', 'img_size': 384, 'n_frames': 175,
            'backbone': 'swin_tiny_patch4_window7_224.ms_in1k', 'window_size': 0,
            'aggregator': 'mean',
            'use_classifier': True, 'cls_weight': 0.3, 'num_classes': 4,
            'cls_thresholds': [6.4, 16.3, 20.7],
            'loss_fn': 'l1', 'loss_config': {}, 'loss_preset': None,
            'epochs': 100, 'batch_size': 1, 'grad_accum': 8,
            'lr': 1e-4, 'wd': 1e-4, 'workers': 2, 'seed': 42,
            'threshold': 5.0, 'use_weighted_sampler': True,
            'n_folds': 5, 'fold_set_prefix': 'set', 'set_col': 'set1',
            'output_dir': '', 'run_name': '', 'device': None,
        }

        # Apply defaults then override with kwargs
        for k, v in defaults.items():
            setattr(self, k, kwargs.get(k, v))

        # Set device
        if self.device is None:
            torch = _get_torch()
            self.device = "cuda" if torch.cuda.is_available() else "cpu"

        # Convert paths
        self.video_folder = Path(self.video_folder) if self.video_folder else Path(".")
        self.csv_path = Path(self.csv_path) if self.csv_path else Path(".")
        self.cache_dir = Path(self.cache_dir) if self.cache_dir else Path(".")
        self.output_dir = Path(self.output_dir) if self.output_dir else Path(".")

        # Ensure loss_config is dict
        if self.loss_config is None:
            self.loss_config = {}

        # Auto run name
        if not self.run_name:
            self.run_name = self._make_run_name()

        # Set experiment directory
        self.exp_dir = self.output_dir / self.run_name
        self.exp_dir.mkdir(parents=True, exist_ok=True)

        # Save config
        self._save()

    def _make_run_name(self) -> str:
        parts = [self.aggregator, f"s{self.img_size}", f"f{self.n_frames}"]
        if self.loss_preset:
            parts.append(f"loss_{self.loss_preset}")
        elif self.loss_fn != "l1":
            parts.append(f"loss_{self.loss_fn}")
        if self.use_classifier:
            parts.append(f"cls{int(self.cls_weight * 100)}")
        if self.n_folds > 0:
            parts.append(f"CV{self.n_folds}")
        return "_".join(parts)

    def _save(self):
        import json
        data = {k: getattr(self, k) for k in self.__slots__}
        with open(self.exp_dir / "config.json", "w") as f:
            json.dump(data, f, indent=2, default=str)


def load_config(yaml_path: str) -> CFG:
    """
    Load configuration from YAML file.

    Usage:
        cfg = load_config("configs/experiment.yaml")
    """
    import yaml

    with open(yaml_path, "r") as f:
        data = yaml.safe_load(f)

    print(f"[CONFIG] Loaded: {yaml_path}")
    return CFG(**data)


def set_seed(seed: int):
    """Set random seed for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch = _get_torch()
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
